import Vue from 'vue';
import AAction from '~/components/global/AAction.vue';
import AButton from '~/components/global/AButton.vue';
import AButtonSimple from '~/components/global/AButtonSimple.vue';
import ACarousel from '~/components/global/ACarousel.vue';
import ACheckList from '~/components/global/ACheckList.vue';
import AJson from '~/components/global/AJson.vue';
import ALoading from '~/components/global/ALoading.vue';
import ANotebook from '~/components/global/ANotebook.vue';
import ANotes from '~/components/global/ANotes.vue';
import ANotFound from '~/components/global/ANotFound.vue';
import APersonList from '~/components/global/APersonList.vue';
import ASquareList from '~/components/global/ASquareList.vue';
import APicture from '~/components/global/APicture.vue';
import AStates from '~/components/global/AStates.vue';
import ATitle from '~/components/global/ATitle.vue';

Vue.component('AAction', AAction);
Vue.component('AButton', AButton);
Vue.component('AButtonSimple', AButtonSimple);
Vue.component('ACarousel', ACarousel);
Vue.component('ACheckList', ACheckList);
Vue.component('AJson', AJson);
Vue.component('ALoading', ALoading);
Vue.component('ANotebook', ANotebook);
Vue.component('ANotes', ANotes);
Vue.component('ANotFound', ANotFound);
Vue.component('APersonList', APersonList);
Vue.component('ASquareList', ASquareList);
Vue.component('AStates', AStates);
Vue.component('APicture', APicture);
Vue.component('ATitle', ATitle);
